#!/usr/bin/env bash
# junto-setup.sh — first-time setup wizard for new Junto users.
#
# Usage:
#   ~/.junto/junto-setup.sh
#
# Run once per machine. Prompts for name, API key, server URL, and project
# directory, then writes ~/.junto/config, creates a starter CLAUDE.md in
# the project directory, and launches Claude in first-run onboarding mode.
#
# After setup, use the standard launcher for all future sessions:
#   cd <project-dir> && ~/.junto/junto-launch.sh

set -euo pipefail

JUNTO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="${JUNTO_DIR}/config"
FIRST_RUN_OVERLAY="${JUNTO_DIR}/templates/overlays/first-run.md"

echo ""
echo "=== Junto First-Run Setup ==="
echo ""

# ── Prerequisites ──────────────────────────────────────────────────────────────

if ! command -v claude &>/dev/null; then
    echo "ERROR: 'claude' CLI not found. Install Claude Code first."
    echo "  https://claude.ai/code"
    exit 1
fi

if ! command -v curl &>/dev/null; then
    echo "ERROR: 'curl' is required but not found."
    exit 1
fi

# ── Collect user info ──────────────────────────────────────────────────────────

read -rp "Your first name (will become junto{Name} agent identity, e.g. juntoSarah): " USER_FIRST
if [[ -z "$USER_FIRST" ]]; then
    echo "ERROR: Name cannot be empty." >&2; exit 1
fi
# Capitalize first letter
USER_FIRST="${USER_FIRST^}"
JUNTO_AGENT="junto${USER_FIRST}"
echo "  Agent identity: ${JUNTO_AGENT}"
echo ""

echo "Paste your Junto API key (starts with smk_):"
read -rp "API key: " JUNTO_API_KEY
if [[ -z "$JUNTO_API_KEY" ]]; then
    echo "ERROR: API key cannot be empty." >&2; exit 1
fi
echo ""

DEFAULT_URL="http://spg-junto-central:8080/mcp"
read -rp "Server URL [${DEFAULT_URL}]: " url_input
JUNTO_MEMORY_URL="${url_input:-$DEFAULT_URL}"
echo ""

read -rp "Path to your awareness project directory (created if it doesn't exist): " PROJECT_DIR
PROJECT_DIR="${PROJECT_DIR/#\~/$HOME}"
PROJECT_DIR="$(realpath -m "$PROJECT_DIR")"
mkdir -p "$PROJECT_DIR"
echo "  Project dir: ${PROJECT_DIR}"
echo ""

# ── Write config ───────────────────────────────────────────────────────────────

cat > "$CONFIG" << EOF
# Junto local configuration — generated by junto-setup.sh
# Edit these values for your machine. Do not commit this file.

# API key for the shared memory server
JUNTO_API_KEY="${JUNTO_API_KEY}"

# Shared memory server URL
JUNTO_MEMORY_URL="${JUNTO_MEMORY_URL}"

# Agent identity
JUNTO_AGENT="${JUNTO_AGENT}"

# Default project
JUNTO_PROJECT="awareness"

# Role description
JUNTO_ROLE="Awareness team agent"
EOF
chmod 600 "$CONFIG"
echo "Config written to ${CONFIG}"

# ── Write CLAUDE.md ────────────────────────────────────────────────────────────

CLAUDE_MD="${PROJECT_DIR}/CLAUDE.md"
if [[ ! -f "$CLAUDE_MD" ]]; then
    cat > "$CLAUDE_MD" << EOF
# Awareness Project

Your name is: \`${JUNTO_AGENT}\`

This is the awareness project CLAUDE.md. Add repo-specific orientation below.
For operational rules and session protocol, those come from the junto system
prompt (injected at launch via --append-system-prompt-file).

<!-- junto identity markers — used by junto-launch.sh for auto-detection -->
<!-- project="awareness" -->
EOF
    echo "CLAUDE.md created at ${CLAUDE_MD}"
else
    echo "CLAUDE.md already exists at ${CLAUDE_MD} — skipping creation"
    echo "  Make sure it contains: Your name is: \`${JUNTO_AGENT}\`"
fi
echo ""

# ── Connectivity check ─────────────────────────────────────────────────────────

# Strip trailing /mcp to get the base URL for the health endpoint
BASE_URL="${JUNTO_MEMORY_URL%/mcp}"
echo -n "Testing server connectivity at ${BASE_URL}/health ... "
if curl -sf "${BASE_URL}/health" &>/dev/null; then
    echo "OK"
else
    echo "UNREACHABLE"
    echo ""
    echo "  Warning: the server is not reachable right now."
    echo "  If you're using spg-junto-central, you must be on the LVT tailnet."
    echo "  On WSL2: check that ~/.wslconfig has [wsl2] networkingMode=mirrored"
    echo "  You can proceed — the agent will report the issue when it starts."
fi
echo ""

# ── Launch in first-run onboarding mode ───────────────────────────────────────

echo "Launching ${JUNTO_AGENT}@awareness in first-run onboarding mode..."
echo "(Your agent will walk you through the rest of the setup.)"
echo ""

cd "$PROJECT_DIR"
export JUNTO_OVERLAY="${FIRST_RUN_OVERLAY}"
exec bash "${JUNTO_DIR}/junto-launch.sh"
