#Requires -Version 5.1
<#
.SYNOPSIS
    junto-workspace.ps1 -- unified junto workspace setup and launcher (Windows).

.DESCRIPTION
    Windows counterpart to junto-workspace.sh. Same three-phase flow:

    Phase 1 -- Machine setup: loads ~/.junto/config (API key, server URL).
               If missing, runs setup wizard, writes config, registers MCP
               server, creates hooks and settings.

    Phase 2 -- Project identity: reads .agent-name + .project-name (fast path),
               falls back to CLAUDE.md walk-up, falls back to interactive wizard
               that writes CLAUDE.md + .agent-name + .project-name + settings.local.json.

    Phase 3 -- Launch: renders system prompt and starts claude.

    Replaces junto-setup.ps1 + junto-init.ps1 + junto-launch.ps1 for new users.
    Existing users can continue using junto-launch.ps1 directly; workspace.ps1
    is the recommended entry point going forward.

.PARAMETER NoPlugin
    Disable junto-inbox channel push (push is on by default).

.PARAMETER ClaudeArgs
    Additional arguments forwarded to claude.

.EXAMPLE
    cd C:\code\my-project
    & "$HOME\.junto\junto-workspace.ps1"

.NOTES
    Recommended alias in your PowerShell profile:
      Set-Alias junto "$HOME\.junto\junto-workspace.ps1"
#>

[CmdletBinding()]
param(
    [switch]$NoPlugin,
    [Parameter(ValueFromRemainingArguments)][string[]]$ClaudeArgs
)

$ErrorActionPreference = 'Stop'

$JuntoDir     = Split-Path -Parent $MyInvocation.MyCommand.Path
$ConfigPath   = Join-Path $JuntoDir 'config'
$TemplatesDir = Join-Path $JuntoDir 'templates'

# ── Phase 1: Machine config ────────────────────────────────────────────────────

function Invoke-MachineSetup {
    Write-Host ""
    Write-Host "=== junto: first-time machine setup ===" -ForegroundColor Cyan
    Write-Host "No config found at $ConfigPath." -ForegroundColor Yellow
    Write-Host ""

    # API key
    $juntoKey = (Read-Host "Junto API key (starts with smk_)").Trim()
    if ([string]::IsNullOrEmpty($juntoKey)) { Write-Error "API key cannot be empty."; exit 1 }

    # Server URL
    $defaultUrl = 'http://spg-junto-central:8080/mcp'
    $urlInput   = (Read-Host "Server URL [$defaultUrl]").Trim()
    $juntoUrl   = if ([string]::IsNullOrEmpty($urlInput)) { $defaultUrl } else { $urlInput }
    Write-Host ""

    # Write ~/.junto/config
    Set-Content -Path $ConfigPath -Encoding utf8 -Value @"
# Junto local configuration -- generated by junto-workspace.ps1
# Do not commit this file.

JUNTO_API_KEY="$juntoKey"
JUNTO_MEMORY_URL="$juntoUrl"
JUNTO_ROLE="General work agent"
"@
    [System.IO.File]::SetAttributes($ConfigPath, [System.IO.FileAttributes]::Normal)
    Write-Host "junto: config written to $ConfigPath" -ForegroundColor Green

    # Register MCP server in ~/.mcp.json (with Bearer auth)
    $mcpPath = Join-Path $HOME '.mcp.json'
    try   { $mcpData = Get-Content -Raw $mcpPath -ErrorAction Stop | ConvertFrom-Json }
    catch { $mcpData = [PSCustomObject]@{} }
    if (-not $mcpData.PSObject.Properties['mcpServers']) {
        $mcpData | Add-Member -NotePropertyName 'mcpServers' -NotePropertyValue ([PSCustomObject]@{}) -Force
    }
    $mcpData.mcpServers | Add-Member -NotePropertyName 'junto' -NotePropertyValue ([PSCustomObject]@{
        type    = 'http'
        url     = $juntoUrl
        headers = [PSCustomObject]@{ Authorization = "Bearer $juntoKey" }
    }) -Force
    $mcpData | ConvertTo-Json -Depth 10 | Set-Content -Path $mcpPath -Encoding utf8
    Write-Host "junto: MCP server registered in $mcpPath" -ForegroundColor Green

    # Create managed-remote-settings.json
    $claudeDir   = Join-Path $HOME '.claude'
    if (-not (Test-Path $claudeDir)) { New-Item -ItemType Directory -Path $claudeDir -Force | Out-Null }
    $managedPath = Join-Path $claudeDir 'managed-remote-settings.json'
    $pluginEntry = [PSCustomObject]@{ marketplace = 'tlemmons-junto-inbox'; plugin = 'junto-inbox' }
    if (-not (Test-Path $managedPath)) {
        [PSCustomObject]@{
            channelsEnabled       = $true
            allowedChannelPlugins = @($pluginEntry)
        } | ConvertTo-Json -Depth 5 | Set-Content -Path $managedPath -Encoding utf8
        Write-Host "junto: created $managedPath" -ForegroundColor Green
    } else {
        try { $ms = Get-Content -Raw $managedPath | ConvertFrom-Json } catch { $ms = [PSCustomObject]@{} }
        $changed = $false
        if (-not $ms.channelsEnabled) {
            $ms | Add-Member -NotePropertyName 'channelsEnabled' -NotePropertyValue $true -Force; $changed = $true
        }
        $existing = @($ms.allowedChannelPlugins)
        if (-not ($existing | Where-Object { $_.marketplace -eq 'tlemmons-junto-inbox' -and $_.plugin -eq 'junto-inbox' })) {
            $ms | Add-Member -NotePropertyName 'allowedChannelPlugins' -NotePropertyValue ($existing + $pluginEntry) -Force; $changed = $true
        }
        if ($changed) { $ms | ConvertTo-Json -Depth 5 | Set-Content -Path $managedPath -Encoding utf8 }
    }

    # Create ensure-channel-settings.ps1 hook
    $hooksDir   = Join-Path $claudeDir 'hooks'
    if (-not (Test-Path $hooksDir)) { New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null }
    $hookScript = Join-Path $hooksDir 'ensure-channel-settings.ps1'
    Set-Content -Path $hookScript -Encoding utf8 -Value @'
# Restores channelsEnabled + allowedChannelPlugins to remote-settings.json
# in case Claude Code overwrites it with a fresh org-policy fetch.
$remote = Join-Path $HOME ".claude\remote-settings.json"
try { $data = Get-Content -Raw $remote -ErrorAction Stop | ConvertFrom-Json }
catch { $data = [PSCustomObject]@{} }
$changed = $false
if (-not $data.PSObject.Properties['channelsEnabled'] -or -not $data.channelsEnabled) {
    $data | Add-Member -NotePropertyName 'channelsEnabled' -NotePropertyValue $true -Force
    $changed = $true
}
$entry    = [PSCustomObject]@{ marketplace = 'tlemmons-junto-inbox'; plugin = 'junto-inbox' }
$existing = @($data.allowedChannelPlugins)
if (-not ($existing | Where-Object { $_.marketplace -eq 'tlemmons-junto-inbox' -and $_.plugin -eq 'junto-inbox' })) {
    $data | Add-Member -NotePropertyName 'allowedChannelPlugins' -NotePropertyValue ($existing + $entry) -Force
    $changed = $true
}
if ($changed) {
    $data | ConvertTo-Json -Depth 5 | Set-Content -Path $remote -Encoding utf8
    Write-Host "[ensure-channel-settings] Restored channel keys to $remote"
}
'@
    Write-Host "junto: hook created at $hookScript" -ForegroundColor Green

    # Update ~/.claude/settings.json
    $settingsPath = Join-Path $claudeDir 'settings.json'
    try   { $settings = Get-Content -Raw $settingsPath -ErrorAction Stop | ConvertFrom-Json }
    catch { $settings = [PSCustomObject]@{} }

    if (-not $settings.PSObject.Properties['extraKnownMarketplaces']) {
        $settings | Add-Member -NotePropertyName 'extraKnownMarketplaces' -NotePropertyValue ([PSCustomObject]@{}) -Force
    }
    $settings.extraKnownMarketplaces | Add-Member -NotePropertyName 'tlemmons-junto-inbox' -NotePropertyValue (
        [PSCustomObject]@{ source = [PSCustomObject]@{ source = 'github'; repo = 'tlemmons/junto-inbox' } }
    ) -Force
    if (-not $settings.PSObject.Properties['enabledPlugins']) {
        $settings | Add-Member -NotePropertyName 'enabledPlugins' -NotePropertyValue ([PSCustomObject]@{}) -Force
    }
    $settings.enabledPlugins | Add-Member -NotePropertyName 'junto-inbox@tlemmons-junto-inbox' -NotePropertyValue $true -Force
    $settings | Add-Member -NotePropertyName 'channelsEnabled' -NotePropertyValue $true -Force
    if (-not $settings.PSObject.Properties['allowedChannelPlugins']) {
        $settings | Add-Member -NotePropertyName 'allowedChannelPlugins' -NotePropertyValue @() -Force
    }
    $existingPlugins = @($settings.allowedChannelPlugins)
    if (-not ($existingPlugins | Where-Object { $_.marketplace -eq 'tlemmons-junto-inbox' })) {
        $settings | Add-Member -NotePropertyName 'allowedChannelPlugins' -NotePropertyValue (
            $existingPlugins + $pluginEntry
        ) -Force
    }
    if (-not $settings.PSObject.Properties['model']) {
        $settings | Add-Member -NotePropertyName 'model' -NotePropertyValue 'opusplan' -Force
    }
    if (-not $settings.PSObject.Properties['env']) {
        $settings | Add-Member -NotePropertyName 'env' -NotePropertyValue ([PSCustomObject]@{}) -Force
    }
    $settings.env | Add-Member -NotePropertyName 'CLAUDE_CODE_REMOTE_SETTINGS_PATH' -NotePropertyValue $managedPath -Force

    $hookCmd   = "powershell.exe -NoProfile -NonInteractive -File `"$hookScript`""
    $hookEntry = [PSCustomObject]@{ type = 'command'; command = $hookCmd }
    if (-not $settings.PSObject.Properties['hooks']) {
        $settings | Add-Member -NotePropertyName 'hooks' -NotePropertyValue ([PSCustomObject]@{}) -Force
    }
    foreach ($event in 'Stop', 'UserPromptSubmit') {
        if (-not $settings.hooks.PSObject.Properties[$event]) {
            $settings.hooks | Add-Member -NotePropertyName $event -NotePropertyValue @() -Force
        }
        $eventHooks = @($settings.hooks.$event)
        $alreadyWired = $eventHooks | Where-Object { ($_.hooks | Where-Object { $_.command -eq $hookCmd }) }
        if (-not $alreadyWired) {
            $settings.hooks.$event = $eventHooks + [PSCustomObject]@{ hooks = @($hookEntry) }
        }
    }
    $settings | ConvertTo-Json -Depth 10 | Set-Content -Path $settingsPath -Encoding utf8
    Write-Host "junto: settings updated in $settingsPath" -ForegroundColor Green

    Write-Host ""
    Write-Host "junto: machine setup complete." -ForegroundColor Green
    Write-Host ""

    # Set process env for rest of launch
    $env:JUNTO_API_KEY    = $juntoKey
    $env:JUNTO_MEMORY_URL = $juntoUrl
}

# Load existing config (does not override env vars already set in the shell)
if (Test-Path $ConfigPath) {
    Get-Content $ConfigPath | ForEach-Object {
        if ($_ -match '^\s*([A-Z_][A-Z0-9_]*)="([^"]*)"' -and $_ -notmatch '^\s*#') {
            $varName = $Matches[1]; $varValue = $Matches[2]
            if (-not [System.Environment]::GetEnvironmentVariable($varName, 'Process')) {
                [System.Environment]::SetEnvironmentVariable($varName, $varValue, 'Process')
            }
        }
    }
} elseif ($Host.Name -eq 'ConsoleHost' -and -not [System.Console]::IsOutputRedirected) {
    Invoke-MachineSetup
} else {
    Write-Error "junto-workspace: $ConfigPath not found. Run junto-workspace.ps1 interactively to complete machine setup."
    exit 1
}

# ── Phase 2: Project identity ──────────────────────────────────────────────────

$cwd             = (Get-Location).Path
$claudeMdPath    = Join-Path $cwd 'CLAUDE.md'
$agentNameFile   = Join-Path $cwd '.agent-name'
$projectNameFile = Join-Path $cwd '.project-name'

function Find-ClaudeMd {
    if (Test-Path $claudeMdPath) { return }
    $dir = Split-Path -Parent $cwd
    while ($dir -ne $HOME -and $dir -ne (Split-Path -Parent $dir)) {
        $candidate = Join-Path $dir 'CLAUDE.md'
        if (Test-Path $candidate) { $script:claudeMdPath = $candidate; return }
        $dir = Split-Path -Parent $dir
    }
}

function Read-AgentNameFile {
    if ($env:JUNTO_AGENT) { return }
    if (-not (Test-Path $agentNameFile)) { return }
    $a = (Get-Content $agentNameFile -First 1 -ErrorAction SilentlyContinue).Trim()
    if ($a) { $env:JUNTO_AGENT = $a }
}

function Read-ProjectNameFile {
    if ($env:JUNTO_PROJECT) { return }
    if (-not (Test-Path $projectNameFile)) { return }
    $p = (Get-Content $projectNameFile -First 1 -ErrorAction SilentlyContinue).Trim()
    if ($p) { $env:JUNTO_PROJECT = $p }
}

function Read-ClaudeMd {
    if ($env:JUNTO_AGENT -and $env:JUNTO_PROJECT) { return }
    if (-not (Test-Path $claudeMdPath)) { return }
    $content = Get-Content $claudeMdPath -Raw -ErrorAction SilentlyContinue
    if (-not $env:JUNTO_AGENT) {
        if ($content -match 'Your name is:[ \t]*`([^`]+)`') { $env:JUNTO_AGENT = $Matches[1] }
    }
    if (-not $env:JUNTO_PROJECT) {
        if ($content -match 'project="([^"]+)"') { $env:JUNTO_PROJECT = $Matches[1] }
    }
    if (-not $env:JUNTO_COMPONENT) {
        if ($content -match 'component="([^"]+)"') { $env:JUNTO_COMPONENT = $Matches[1] }
    }
}

Find-ClaudeMd
Read-AgentNameFile
Read-ProjectNameFile
Read-ClaudeMd

$SetupMode = $false
if (-not $env:JUNTO_AGENT -or -not $env:JUNTO_PROJECT) {
    if ($Host.Name -eq 'ConsoleHost' -and -not [System.Console]::IsOutputRedirected) {
        # No identity found — launch CC as a setup assistant.
        # CC will call memory_list_projects, ask the user for identity, write the
        # files, and instruct a restart. The user runs junto-workspace.ps1 again
        # and the second launch proceeds normally with the written identity.
        $SetupMode = $true
        $env:JUNTO_AGENT   = 'ws-setup'
        $env:JUNTO_PROJECT = 'junto'
        $env:JUNTO_ROLE    = 'Workspace setup assistant'
        $env:JUNTO_OVERLAY = Join-Path $JuntoDir 'templates\overlays\workspace-setup.md'
        # Create settings.local.json before launching so the setup session has
        # access to the full junto MCP tool suite (needed for memory_list_projects).
        $projectClaudeDir = Join-Path $cwd '.claude'
        if (-not (Test-Path $projectClaudeDir)) { New-Item -ItemType Directory -Path $projectClaudeDir -Force | Out-Null }
        $localSettings = Join-Path $projectClaudeDir 'settings.local.json'
        if (-not (Test-Path $localSettings)) {
            [PSCustomObject]@{
                permissions                = [PSCustomObject]@{ allow = @('mcp__junto__*', 'mcp__plugin_junto-inbox_junto-inbox__*') }
                enableAllProjectMcpServers = $true
                enabledMcpjsonServers      = @('junto')
            } | ConvertTo-Json -Depth 5 | Set-Content -Path $localSettings -Encoding utf8
        }
        Write-Host "junto: no workspace identity found -- launching setup assistant..." -ForegroundColor Cyan
        Write-Host "junto: answer the questions, then run junto-workspace.ps1 again to start your session." -ForegroundColor Cyan
    } else {
        if (-not $env:JUNTO_AGENT)   { $env:JUNTO_AGENT   = Split-Path -Leaf $cwd }
        if (-not $env:JUNTO_PROJECT) { $env:JUNTO_PROJECT = Split-Path -Leaf $cwd }
        Write-Host "junto-workspace: no identity found in $cwd, using $($env:JUNTO_AGENT)@$($env:JUNTO_PROJECT)" -ForegroundColor Yellow
        Write-Host "  Launch interactively to set up identity for this directory." -ForegroundColor Yellow
    }
}

# Write fast-path files only on normal launches.
# In setup mode CC writes them; writing ws-setup/junto here would be wrong.
if (-not $SetupMode) {
    if (-not (Test-Path $agentNameFile))   { Set-Content -Path $agentNameFile   -Value $env:JUNTO_AGENT   -Encoding utf8 -NoNewline }
    if (-not (Test-Path $projectNameFile)) { Set-Content -Path $projectNameFile -Value $env:JUNTO_PROJECT -Encoding utf8 -NoNewline }
}

# ── Phase 3: Launch ────────────────────────────────────────────────────────────

if (-not $env:JUNTO_ROLE)       { $env:JUNTO_ROLE       = 'General work agent' }
if (-not $env:JUNTO_MEMORY_URL) { $env:JUNTO_MEMORY_URL = 'http://your-junto-server:8080/mcp' }
if (-not $env:JUNTO_COMPONENT)  { $env:JUNTO_COMPONENT  = '' }

if (-not $env:JUNTO_API_KEY) {
    Write-Error "junto-workspace: JUNTO_API_KEY is not set. Check $ConfigPath."
    exit 1
}

# Bridge env var name: plugin reads JUNTO_SHARED_MEMORY_URL; config uses JUNTO_MEMORY_URL.
$env:JUNTO_SHARED_MEMORY_URL = $env:JUNTO_MEMORY_URL

# Pre-flight: ensure channel settings in remote-settings.json
if (-not $NoPlugin) {
    $hookScript = Join-Path $HOME '.claude\hooks\ensure-channel-settings.ps1'
    if (Test-Path $hookScript) {
        & powershell.exe -NoProfile -NonInteractive -File $hookScript
    }
}

# Render the system prompt
$promptFile = [System.IO.Path]::Combine([System.IO.Path]::GetTempPath(), "junto-$($env:JUNTO_AGENT)-$($env:JUNTO_PROJECT)-prompt.md")
$renderArgs = @{
    Agent           = $env:JUNTO_AGENT
    Project         = $env:JUNTO_PROJECT
    Role            = $env:JUNTO_ROLE
    SharedMemoryUrl = $env:JUNTO_MEMORY_URL
    Cwd             = $cwd
    ApiKey          = $env:JUNTO_API_KEY
    PluginPresent   = (-not $NoPlugin.IsPresent)
    Out             = $promptFile
}
if ($env:JUNTO_OVERLAY -and (Test-Path $env:JUNTO_OVERLAY)) {
    $renderArgs['Overlay'] = $env:JUNTO_OVERLAY
}
& (Join-Path $TemplatesDir 'render.ps1') @renderArgs | Out-Null

# Opt into Sonnet 1M context window
if (-not $env:ANTHROPIC_DEFAULT_SONNET_MODEL) {
    $env:ANTHROPIC_DEFAULT_SONNET_MODEL = 'claude-sonnet-4-6[1m]'
}

# Point Claude Code at our stable remote-settings file
$managedSettings = Join-Path $HOME '.claude\managed-remote-settings.json'
if (Test-Path $managedSettings -and -not $env:CLAUDE_CODE_REMOTE_SETTINGS_PATH) {
    $env:CLAUDE_CODE_REMOTE_SETTINGS_PATH = $managedSettings
}

$_ctx = "$($env:JUNTO_AGENT)@$($env:JUNTO_PROJECT)"
if ($env:JUNTO_COMPONENT) { $_ctx += ":$($env:JUNTO_COMPONENT)" }
Write-Host "junto: launching $_ctx -> $($env:JUNTO_MEMORY_URL)" -ForegroundColor Cyan
if (-not $NoPlugin) { Write-Host "junto: push plugin enabled" -ForegroundColor Cyan }

$allClaudeArgs = @('--append-system-prompt-file', $promptFile)
if (-not $NoPlugin) {
    $allClaudeArgs += '--dangerously-load-development-channels'
    $allClaudeArgs += 'plugin:junto-inbox@tlemmons-junto-inbox'
}
if ($ClaudeArgs) { $allClaudeArgs += $ClaudeArgs }

& claude @allClaudeArgs
