#!/usr/bin/env bash
# junto-workspace.sh — unified junto workspace setup and launcher.
#
# Usage:
#   cd ~/code/my-project
#   ~/.junto/junto-workspace.sh [--no-plugin] [claude args...]
#
# Options:
#   --no-plugin   Disable junto-inbox channel push (push is on by default).
#
# What it does:
#   Phase 1 — Machine setup: loads ~/.junto/config (API key, server URL).
#              If missing and interactive, runs setup wizard, writes config,
#              registers MCP server, creates hooks and settings.
#   Phase 2 — Project identity: reads .agent-name + .project-name (fast path),
#              falls back to CLAUDE.md walk-up, falls back to interactive wizard
#              that writes CLAUDE.md + .agent-name + .project-name + settings.local.json.
#   Phase 3 — Launch: renders system prompt and exec's claude.
#
# Environment overrides (also settable in ~/.junto/config):
#   JUNTO_AGENT       Agent name          (default: prompted or cwd basename)
#   JUNTO_PROJECT     Project name        (default: prompted or cwd basename)
#   JUNTO_ROLE        One-line role       (default: General work agent)
#   JUNTO_MEMORY_URL  MCP server URL      (required, set during machine setup)
#   JUNTO_API_KEY     MCP API key         (required, set during machine setup)
#   JUNTO_OVERLAY     Path to overlay .md (optional)

set -euo pipefail

JUNTO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="${JUNTO_DIR}/config"
TEMPLATES="${JUNTO_DIR}/templates"

# ── Parse flags ───────────────────────────────────────────────────────────────

PLUGIN=true
CLAUDE_ARGS=()
for arg in "$@"; do
    if [[ "$arg" == "--no-plugin" ]]; then PLUGIN=false
    else CLAUDE_ARGS+=("$arg")
    fi
done

# ── Phase 1: Machine config ───────────────────────────────────────────────────

_ws_machine_setup() {
    echo "" >&2
    echo "=== junto: first-time machine setup ===" >&2
    echo "No config found at ${CONFIG}." >&2
    echo "" >&2

    local junto_key junto_url
    local default_url="http://spg-junto-central:8080/mcp"

    # API key
    printf "Junto API key (starts with smk_): " >/dev/tty
    read -rs junto_key </dev/tty; echo "" >/dev/tty
    if [[ -z "$junto_key" ]]; then
        echo "ERROR: API key cannot be empty." >&2; exit 1
    fi

    # Server URL
    printf "Server URL [%s]: " "$default_url" >/dev/tty
    read -r junto_url </dev/tty
    junto_url="${junto_url:-$default_url}"
    echo "" >/dev/tty

    # Write ~/.junto/config
    cat > "$CONFIG" << EOF
# Junto local configuration — generated by junto-workspace.sh
# Do not commit this file.

JUNTO_API_KEY="${junto_key}"
JUNTO_MEMORY_URL="${junto_url}"
JUNTO_ROLE="General work agent"
EOF
    chmod 600 "$CONFIG"
    echo "junto: config written to ${CONFIG}" >&2

    # Register MCP server in ~/.mcp.json (with Bearer auth)
    local mcp_json="${HOME}/.mcp.json"
    python3 - "$mcp_json" "$junto_url" "$junto_key" << 'PYEOF'
import json, sys
path, url, key = sys.argv[1], sys.argv[2], sys.argv[3]
try:
    with open(path) as f: data = json.load(f)
except Exception: data = {}
data.setdefault("mcpServers", {})["junto"] = {
    "type": "http",
    "url": url,
    "headers": {"Authorization": f"Bearer {key}"}
}
with open(path, "w") as f: json.dump(data, f, indent=2)
print(f"junto: MCP server registered in {path}")
PYEOF

    # Create managed-remote-settings.json (keeps channelsEnabled safe from org-policy resets)
    local managed="${HOME}/.claude/managed-remote-settings.json"
    if [[ ! -f "$managed" ]]; then
        cat > "$managed" << 'EOF'
{
  "channelsEnabled": true,
  "allowedChannelPlugins": [
    { "marketplace": "tlemmons-junto-inbox", "plugin": "junto-inbox" }
  ]
}
EOF
        echo "junto: created ${managed}" >&2
    else
        python3 - "$managed" << 'PYEOF'
import json, sys
path = sys.argv[1]
try:
    with open(path) as f: data = json.load(f)
except Exception: data = {}
changed = False
if not data.get("channelsEnabled"):
    data["channelsEnabled"] = True; changed = True
entry = {"marketplace": "tlemmons-junto-inbox", "plugin": "junto-inbox"}
existing = data.get("allowedChannelPlugins", [])
keys = {(p.get("marketplace"), p.get("plugin")) for p in existing}
if (entry["marketplace"], entry["plugin"]) not in keys:
    existing.append(entry); data["allowedChannelPlugins"] = existing; changed = True
if changed:
    with open(path, "w") as f: json.dump(data, f, indent=2)
    print(f"junto: merged channel entries into {path}")
PYEOF
    fi

    # Create ensure-channel-settings.sh hook
    mkdir -p "${HOME}/.claude/hooks"
    local hook="${HOME}/.claude/hooks/ensure-channel-settings.sh"
    cat > "$hook" << 'BASH_EOF'
#!/bin/bash
# Restores channelsEnabled + allowedChannelPlugins to remote-settings.json
# in case Claude Code overwrites it with a fresh org-policy fetch.
REMOTE="$HOME/.claude/remote-settings.json"
python3 - "$REMOTE" <<'EOF'
import sys, json
path = sys.argv[1]
try:
    with open(path, 'r') as f: data = json.load(f)
except Exception: data = {}
changed = False
if not data.get('channelsEnabled'):
    data['channelsEnabled'] = True; changed = True
desired = [{"marketplace": "tlemmons-junto-inbox", "plugin": "junto-inbox"}]
existing = data.get('allowedChannelPlugins', [])
existing_keys = {(e.get('marketplace'), e.get('plugin')) for e in existing}
desired_keys = {(p['marketplace'], p['plugin']) for p in desired}
if not desired_keys.issubset(existing_keys):
    data['allowedChannelPlugins'] = existing + [p for p in desired if (p['marketplace'], p['plugin']) not in existing_keys]
    changed = True
if changed:
    with open(path, 'w') as f: json.dump(data, f, indent=2)
    print(f"[ensure-channel-settings] Restored channel keys to {path}", flush=True)
EOF
exit 0
BASH_EOF
    chmod +x "$hook"
    echo "junto: hook created at ${hook}" >&2

    # Update ~/.claude/settings.json
    local settings="${HOME}/.claude/settings.json"
    local managed_path="$managed"
    python3 - "$settings" "$managed_path" << 'PYEOF'
import json, sys
settings_path, managed_path = sys.argv[1], sys.argv[2]
try:
    with open(settings_path) as f: data = json.load(f)
except Exception: data = {}

data.setdefault("extraKnownMarketplaces", {})["tlemmons-junto-inbox"] = {
    "source": {"source": "github", "repo": "tlemmons/junto-inbox"}
}
data.setdefault("enabledPlugins", {})["junto-inbox@tlemmons-junto-inbox"] = True
plugins = data.setdefault("allowedChannelPlugins", [])
entry = {"marketplace": "tlemmons-junto-inbox", "plugin": "junto-inbox"}
if entry not in plugins:
    plugins.append(entry)
data["channelsEnabled"] = True
if "model" not in data:
    data["model"] = "opusplan"
data.setdefault("env", {})["CLAUDE_CODE_REMOTE_SETTINGS_PATH"] = managed_path

hook_cmd = "bash ~/.claude/hooks/ensure-channel-settings.sh"
hook_entry = {"type": "command", "command": hook_cmd}
hooks = data.setdefault("hooks", {})
for event in ["Stop", "UserPromptSubmit"]:
    event_hooks = hooks.setdefault(event, [])
    already = any(
        any(h.get("command") == hook_cmd for h in w.get("hooks", []))
        for w in event_hooks
    )
    if not already:
        event_hooks.append({"hooks": [hook_entry]})

with open(settings_path, "w") as f: json.dump(data, f, indent=2)
print(f"junto: settings updated in {settings_path}")
PYEOF

    echo "" >&2
    echo "junto: machine setup complete." >&2
    echo "" >&2

    # Set env vars for rest of this launch
    JUNTO_API_KEY="$junto_key"
    JUNTO_MEMORY_URL="$junto_url"
}

if [[ -f "$CONFIG" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$CONFIG"
    set +a
elif [[ -t 0 && -t 1 ]]; then
    _ws_machine_setup
else
    echo "junto-workspace: ~/.junto/config not found. Run ~/.junto/junto-workspace.sh interactively to complete machine setup." >&2
    exit 1
fi

# ── Phase 2: Project identity ─────────────────────────────────────────────────

CLAUDE_MD="$(pwd)/CLAUDE.md"
AGENT_NAME_FILE="$(pwd)/.agent-name"
PROJECT_NAME_FILE="$(pwd)/.project-name"

_ws_find_claude_md() {
    [[ -f "$CLAUDE_MD" ]] && return 0
    local dir; dir="$(pwd)"
    while [[ "$dir" != "$HOME" && "$dir" != "/" ]]; do
        dir="$(dirname "$dir")"
        if [[ -f "$dir/CLAUDE.md" ]]; then
            CLAUDE_MD="$dir/CLAUDE.md"; return 0
        fi
    done
    return 0
}

_ws_read_local_files() {
    [[ -n "${JUNTO_AGENT:-}" && -n "${JUNTO_PROJECT:-}" ]] && return 0
    if [[ -f "$AGENT_NAME_FILE" ]]; then
        local a; a=$(head -1 "$AGENT_NAME_FILE" 2>/dev/null | tr -d '[:space:]')
        [[ -n "$a" && -z "${JUNTO_AGENT:-}" ]] && JUNTO_AGENT="$a"
    fi
    if [[ -f "$PROJECT_NAME_FILE" ]]; then
        local p; p=$(head -1 "$PROJECT_NAME_FILE" 2>/dev/null | tr -d '[:space:]')
        [[ -n "$p" && -z "${JUNTO_PROJECT:-}" ]] && JUNTO_PROJECT="$p"
    fi
}

_ws_read_claude_md() {
    [[ -n "${JUNTO_AGENT:-}" && -n "${JUNTO_PROJECT:-}" ]] && return 0
    [[ ! -f "$CLAUDE_MD" ]] && return 0
    if [[ -z "${JUNTO_AGENT:-}" ]]; then
        local a; a=$(grep -m1 'Your name is:.*`' "$CLAUDE_MD" 2>/dev/null \
            | sed 's/.*`\([^`]*\)`.*/\1/' || true)
        [[ -n "$a" ]] && JUNTO_AGENT="$a"
    fi
    if [[ -z "${JUNTO_PROJECT:-}" ]]; then
        local p; p=$(grep -m1 'project="[^"]*"' "$CLAUDE_MD" 2>/dev/null \
            | sed 's/.*project="\([^"]*\)".*/\1/' || true)
        [[ -n "$p" ]] && JUNTO_PROJECT="$p"
    fi
    if [[ -z "${JUNTO_COMPONENT:-}" ]]; then
        local c; c=$(grep -m1 'component="[^"]*"' "$CLAUDE_MD" 2>/dev/null \
            | sed 's/.*component="\([^"]*\)".*/\1/' || true)
        [[ -n "$c" ]] && JUNTO_COMPONENT="$c"
    fi
}

_ws_init_project() {
    local default_agent default_project
    default_agent="${JUNTO_AGENT:-$(basename "$(pwd)")}"
    default_project="$(basename "$(pwd)" | tr '[:upper:]' '[:lower:]' | tr -dc 'a-z0-9-')"

    echo "" >&2
    echo "=== junto: workspace setup ===" >&2
    echo "Directory: $(pwd)" >&2
    echo "" >&2

    printf "  Agent name     [%s]: " "$default_agent" >/dev/tty
    read -r inp_agent </dev/tty
    JUNTO_AGENT="${inp_agent:-$default_agent}"

    printf "  Project name   [%s]: " "$default_project" >/dev/tty
    read -r inp_project </dev/tty
    inp_project="${inp_project:-$default_project}"
    JUNTO_PROJECT="$(echo "$inp_project" | tr '[:upper:]' '[:lower:]' | tr -dc 'a-z0-9_-')"

    printf "  Component/subproject (optional, Enter to skip): " >/dev/tty
    read -r inp_component </dev/tty
    JUNTO_COMPONENT="${inp_component:-}"

    if [[ -z "$JUNTO_AGENT" ]]; then
        echo "ERROR: agent name cannot be empty." >&2; exit 1
    fi
    if [[ -z "$JUNTO_PROJECT" ]]; then
        echo "ERROR: project name cannot be empty." >&2; exit 1
    fi

    # Write CLAUDE.md
    local target_claude_md; target_claude_md="$(pwd)/CLAUDE.md"
    {
        echo "# ${JUNTO_AGENT}"
        echo ""
        echo "Your name is: \`${JUNTO_AGENT}\`"
        echo ""
        echo "<!-- project=\"${JUNTO_PROJECT}\" -->"
        [[ -n "$JUNTO_COMPONENT" ]] && echo "<!-- component=\"${JUNTO_COMPONENT}\" -->"
    } > "$target_claude_md"

    # Write .agent-name and .project-name
    echo "$JUNTO_AGENT" > "$AGENT_NAME_FILE"
    echo "$JUNTO_PROJECT" > "$PROJECT_NAME_FILE"

    # Create .claude/settings.local.json
    local settings_dir; settings_dir="$(pwd)/.claude"
    mkdir -p "$settings_dir"
    if [[ ! -f "${settings_dir}/settings.local.json" ]]; then
        cat > "${settings_dir}/settings.local.json" << 'EOF'
{
  "permissions": {
    "allow": [
      "mcp__junto__*",
      "mcp__plugin_junto-inbox_junto-inbox__*"
    ]
  },
  "enableAllProjectMcpServers": true,
  "enabledMcpjsonServers": ["junto"]
}
EOF
        echo "junto: created .claude/settings.local.json" >&2
    fi

    local ctx="${JUNTO_AGENT}@${JUNTO_PROJECT}"
    [[ -n "$JUNTO_COMPONENT" ]] && ctx="${ctx}:${JUNTO_COMPONENT}"
    echo "" >&2
    echo "junto: workspace initialized — ${ctx}" >&2
    echo "" >&2
}

_ws_find_claude_md
_ws_read_local_files
_ws_read_claude_md

if [[ -z "${JUNTO_AGENT:-}" || -z "${JUNTO_PROJECT:-}" ]]; then
    if [[ -t 0 && -t 1 ]]; then
        _ws_init_project
    else
        JUNTO_AGENT="${JUNTO_AGENT:-$(basename "$(pwd)")}"
        JUNTO_PROJECT="${JUNTO_PROJECT:-$(basename "$(pwd)")}"
        echo "junto-workspace: no identity found in $(pwd), using ${JUNTO_AGENT}@${JUNTO_PROJECT}" >&2
        echo "  Launch interactively to set up identity for this directory." >&2
    fi
fi

# Idempotently write .agent-name and .project-name (fast-path for future launches)
if [[ ! -f "$AGENT_NAME_FILE" ]]; then
    echo "${JUNTO_AGENT}" > "$AGENT_NAME_FILE"
fi
if [[ ! -f "$PROJECT_NAME_FILE" ]]; then
    echo "${JUNTO_PROJECT}" > "$PROJECT_NAME_FILE"
fi

# ── Phase 3: Launch ───────────────────────────────────────────────────────────

JUNTO_ROLE="${JUNTO_ROLE:-General work agent}"
JUNTO_MEMORY_URL="${JUNTO_MEMORY_URL:-http://your-junto-server:8080/mcp}"
JUNTO_COMPONENT="${JUNTO_COMPONENT:-}"

if [[ -z "${JUNTO_API_KEY:-}" ]]; then
    echo "junto-workspace: JUNTO_API_KEY is not set. Check ~/.junto/config." >&2
    exit 1
fi

JUNTO_SHARED_MEMORY_URL="${JUNTO_MEMORY_URL}"
export JUNTO_AGENT JUNTO_PROJECT JUNTO_ROLE JUNTO_MEMORY_URL JUNTO_SHARED_MEMORY_URL JUNTO_CHANNEL_DELAY JUNTO_COMPONENT

# Pre-flight: ensure channel settings in remote-settings.json
if [[ "$PLUGIN" == "true" ]] && [[ -f "${HOME}/.claude/hooks/ensure-channel-settings.sh" ]]; then
    bash "${HOME}/.claude/hooks/ensure-channel-settings.sh"
fi

# Render system prompt
RENDER_ARGS=(
    --agent "$JUNTO_AGENT"
    --project "$JUNTO_PROJECT"
    --role "$JUNTO_ROLE"
    --shared-memory-url "$JUNTO_MEMORY_URL"
    --cwd "$(pwd)"
    --api-key "$JUNTO_API_KEY"
    --out "/tmp/junto-${JUNTO_AGENT}-${JUNTO_PROJECT}-prompt.md"
)
[[ "$PLUGIN" == "true" ]] && RENDER_ARGS+=(--plugin-present true)
[[ -n "${JUNTO_OVERLAY:-}" ]] && RENDER_ARGS+=(--overlay "$JUNTO_OVERLAY")

PROMPT_FILE=$(bash "${TEMPLATES}/render.sh" "${RENDER_ARGS[@]}")

# Opt into Sonnet 1M context window
export ANTHROPIC_DEFAULT_SONNET_MODEL="${ANTHROPIC_DEFAULT_SONNET_MODEL:-claude-sonnet-4-6[1m]}"

# Point Claude Code at our stable remote-settings file
export CLAUDE_CODE_REMOTE_SETTINGS_PATH="${HOME}/.claude/managed-remote-settings.json"

_ctx="${JUNTO_AGENT}@${JUNTO_PROJECT}"
[[ -n "${JUNTO_COMPONENT:-}" ]] && _ctx="${_ctx}:${JUNTO_COMPONENT}"
echo "junto: launching ${_ctx} → ${JUNTO_MEMORY_URL}" >&2
[[ "$PLUGIN" == "true" ]] && echo "junto: push plugin enabled" >&2

if [[ "$PLUGIN" == "true" ]]; then
    exec claude \
        --append-system-prompt-file "$PROMPT_FILE" \
        --dangerously-load-development-channels "plugin:junto-inbox@tlemmons-junto-inbox" \
        ${CLAUDE_ARGS[@]+"${CLAUDE_ARGS[@]}"}
else
    exec claude \
        --append-system-prompt-file "$PROMPT_FILE" \
        ${CLAUDE_ARGS[@]+"${CLAUDE_ARGS[@]}"}
fi
